version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__NET_ID=000000
      - NETWORK_SERVER__BAND__NAME=CN470
      - NETWORK_SERVER__NETWORK_SETTINGS__DISABLE_MAC_COMMANDS=true
      - NETWORK_SERVER__NETWORK_SETTINGS__DISABLE_ADR=true
      - NETWORK_SERVER__NETWORK_SETTINGS__ENABLED_UPLINK_CHANNELS=80,81,82,83,84,85,86,87
      - NETWORK_SERVER__API__BIND=chirpstack-network-server:8000
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://rabbitmq:1883
      - NETWORK_SERVER__GATEWAY__BACKEND__AMQP__SERVER=amqp://guest:guest@rabbitmq:5672
      - NETWORK_SERVER__GATEWAY__BACKEND__AMQP__EVENT_QUEUE_NAME=gateway-events
      - NETWORK_SERVER__GATEWAY__BACKEND__AMQP__EVENT_ROUTING_KEY=gateway.*.event.*
      - NETWORK_SERVER__GATEWAY__BACKEND__AMQP__COMMAND_ROUTING_KEY_TEMPLATE=gateway.{{ .GatewayID }}.command.{{ .CommandType }}
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    ports:
      - 8000:8000
    volumes:
      - $PWD/chirpstack/configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
        #   - mosquitto
      - rabbitmq
    restart: always

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://rabbitmq:1883
      - APPLICATION_SERVER__API__bind=chirpstack-application-server:8001
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
      - JOIN_SERVER__BIND=chirpstack-application-server:8003
    ports:
      - 8080:8080  
    volumes:
      - $PWD/chirpstack/configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server
    restart: always

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    environment:
      - BACKEND__SEMTECH_UDP__SKIP_CRC_CHECK=false
      - INTEGRATION__marshaler=json
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://rabbitmq:1883
      - INTEGRATION__MQTT__AUTH__GENERIC__USERNAME=admin
      - INTEGRATION__MQTT__AUTH__GENERIC__PASSWORD=admin
    ports:
      - 1700:1700/udp
    volumes:
      - $PWD/chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      # - mosquitto
      - rabbitmq
    restart: always

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - $PWD/chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdbdata:/var/lib/influxdb2
      - $PWD/influx/config:/etc/influxdb2
    ports:
      - 8006:8006
      - 2003:2003
      - 8086:8086
      - 8083:8083
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=Asia/Shanghai
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.qq.com:465
      - GF_SMTP_USER=229077035@qq.com
      - GF_SMTP_PASSWORD=rxxorwljqbcnbhce
      - GF_SMTP_FROM_ADDRESS=229077035@qq.com


    ports:
      - 3000:3000 
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: always

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    restart: always

  #mosquitto:
  #image: eclipse-mosquitto:2
  # ports:
  #   - 1883:1883
  # volumes: 
  #   - $PWD/chirpstack/configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  # restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - 15672:15672
      - 1883:1883
      - 5672:5672 
      - 15675:15675 
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - $PWD/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - $PWD/rabbitmq/advanced.conf:/etc/rabbitmq/advanced.conf
      - $PWD/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: always

  frps:
    image: snowdreamtech/frps
    container_name: frps
    volumes:
      - $PWD/frp/frps/frps.ini:/etc/frp/frps.ini
    restart: always
    network_mode: "host"

volumes:
  rabbitmqdata:
  influxdbdata:
  postgresqldata:
  grafana-storage:
  redisdata:
