{
 "title": "Sensing Application",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "choose the device",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"my-bucket\", tag: \"device_name\")"
   },
   {
    "name": "dev_eui",
    "label": "Choose the device address",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"my-bucket\", tag: \"dev_eui\")"
   },
   {
    "name": "frequency",
    "label": "Choose the device frequency",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"my-bucket\", tag: \"frequency\")"
   },
   {
    "name": "dr",
    "label": "Choose the data rate",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"my-bucket\", tag: \"dr\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Link Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> filter(fn: (r) => r[\"frequency\"] == \"${frequency}\")\r\n  |> filter(fn: (r) => r[\"dr\"] == \"${dr}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> filter(fn: (r) => r[\"frequency\"] == \"${frequency}\")\r\n  |> filter(fn: (r) => r[\"dr\"] == \"${dr}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature  and Humidity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_temperatureSensor_1\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_humiditySensor_2\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 3, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_analogInput_3\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_analogInput_4\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"dev_eui\"] == \"${dev_eui}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}