{
 "title": "参数分配机制",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "选择终端节点",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"mechanisms\", tag: \"device_name\")"
   },
   {
    "name": "mechanism_name",
    "label": "选择机制",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"mechanisms\", tag: \"mechanism_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "扩频因子",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mechanisms\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"mechanism_name\"] == \"${mechanism_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spreading_factor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "传输功率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mechanisms\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> filter(fn: (r) => r[\"mechanism_name\"] == \"${mechanism_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transmission _power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "公平性指数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mechanisms\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_statistics_2\")\r\n  |> filter(fn: (r) => r[\"mechanism_name\"] == \"${mechanism_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fairness_index\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "最小能量效率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mechanisms\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"minimal_energy_efficiency\")\r\n  |> filter(fn: (r) => r[\"mechanism_name\"] == \"${mechanism_name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}